### ISSUE TITLE
在vite 3.2.0如果声明依赖项的拆分，会导致项目无法运行，

### ISSUE THREAD

**Issue by lainbo** [sanyuan0704/vite-plugin-chunk-split#12]
```ts
// vite.config.ts
...
import { chunkSplitPlugin } from 'vite-plugin-chunk-split'

export default defineConfig({
  plugins: [
    vue(),
    chunkSplitPlugin({
      strategy: 'default',
      customSplitting: {
        element: ['element-plus'],
      },
    }),
  ]
})
```
如果声明了依赖的拆包，开发环境都无法运行，并报如下错误
`error when starting dev server:
Error: Failed to resolve entry for package "element-plus". The package may have incorrect main/module/exports specified in its package.json: Cannot read properties of undefined (reading 'length')`

### 设备信息
  System:
    OS: Windows 10 10.0.22621
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i7-12700KF
    Memory: 6.02 GB / 15.86 GB
  Binaries:
    Node: 16.17.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
    npm: 8.15.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.675.0), Chromium (106.0.1370.52)
    Internet Explorer: 11.0.22621.1

**Comment by sanyuan0704** [comment]
3.2 的 API 有 break change了，有点头疼

**Comment by sanyuan0704** [comment]
vite-plugin-chunk-split 是最新版本吗

**Comment by sanyuan0704** [comment]
v0.4.3 已经完全修复

**Comment by anncwb** [comment]
@sanyuan0704 好像并没有修复，还是有这个问题

**Comment by sanyuan0704** [comment]
@anncwb 报的是和上面一样的错吗？

**Comment by sanyuan0704** [comment]
@anncwb 你可以拉下这个仓库，https://github.com/sanyuan0704/chunk-split-issue  0.4.3 版本是没问题的，0.4.2 会报issue里面的错

**Comment by anncwb** [comment]
我这边的场景可能复杂些，但是报的一样的错误，我看看怎么提供一个复现的仓库
