### ISSUE TITLE
在Vite@4.4.8上报错

### ISSUE THREAD

**Issue by censujiang** [sanyuan0704/vite-plugin-chunk-split#31]
```console
error when starting dev server:
TypeError: Cannot destructure property 'dir' of 'object null' as it is null.
    at resolvePackageEntry (file:///D:/git/code/node_modules/vite/dist/node/chunks/dep-3b8eb186.js:28605:36)
    at D:\git\code\node_modules\vite-plugin-chunk-split\dist\utils.js:35:16
    at Generator.next (<anonymous>)
    at fulfilled (D:\git\code\node_modules\vite-plugin-chunk-split\dist\utils.js:5:58)
error Command failed with exit code 1.
```

**Comment by censujiang** [comment]
My problem

**Comment by alii** [comment]
Did you find a fix?

**Comment by censujiang** [comment]
> Did you find a fix?

You only need to adjust the functions that need to be imported before to be packaged in the packaged product that will be imported before that.

**Comment by hacker-frok** [comment]
> > Did you find a fix?
> 
> You only need to adjust the functions that need to be imported before to be packaged in the packaged product that will be imported before that.

请问，具体是如何操作的？

**Comment by censujiang** [comment]
> > > Did you find a fix?
> > 
> > 
> > You only need to adjust the functions that need to be imported before to be packaged in the packaged product that will be imported before that.
> 
> 请问，具体是如何操作的？

Just adjust the sub-packaging order of the packages you introduced.
