### ISSUE TITLE
在Vite3中，通过写依赖包名字拆包失效

### ISSUE THREAD

**Issue by lainbo** [sanyuan0704/vite-plugin-chunk-split#4]
在升级了vite3后，按照文档的写法
```js
// vite.config.ts
import { chunkSplitPlugin } from 'vite-plugin-chunk-split';

{
  plugins: [
    // ...
    chunkSplitPlugin({
      strategy: 'single-vendor',
      customSplitting: {
        // `react` and `react-dom` will be bundled together in the `react-vendor` chunk (with their dependencies, such as object-assign)
        'react-vendor': ['react', 'react-dom'],
        // Any file that includes `utils` in src dir will be bundled in the `utils` chunk
        'utils': [/src\/utils/]
      }
    })
  ]
}
```

此时打包，utils文件正常生成，react-vendor这种通过包名的不会生效

相关文件链接：[https://codesandbox.io/s/new-breeze-yizrbj?file=/vite.config.js:303-345](url)

**Comment by sanyuan0704** [comment]
我想这应该是属于 Vite 3.0 对于依赖的处理有 break change，使用 esbuild 打包导致的

**Comment by sanyuan0704** [comment]
这应该和 Vite 3.0 没有关系，之前 single-vendor 模式的处理有点问题。现在我已经发了新版(0.2.5)，目前拆包应该是正常的了

**Comment by lainbo** [comment]
> 这应该和 Vite 3.0 没有关系，之前 single-vendor 模式的处理有点问题。现在我已经发了新版(0.2.5)，目前拆包应该是正常的了

依旧不可以正常工作诶~我如果把vite退回到2.x就是可以的

**Comment by sanyuan0704** [comment]
single-vendor 模式吗？升级了插件版本没？

**Comment by sanyuan0704** [comment]
额，你是不是开了esbuild生产构建模式

**Comment by lainbo** [comment]
> single-vendor 模式吗？升级了插件版本没？

已经升级到0.2.5了
以下是我的vite.config.js
```js
import { defineConfig } from 'vite'
import { resolve } from 'path'
import { chunkSplitPlugin } from 'vite-plugin-chunk-split'
import vue from '@vitejs/plugin-vue'
import Components from 'unplugin-vue-components/vite'
import AutoImport from 'unplugin-auto-import/vite'
import UnoCSS from 'unocss/vite'
import { ArcoResolver } from 'unplugin-vue-components/resolvers'
import { primaryColor } from './src/config/colorConfig.js'

export default defineConfig({
  base: './',
  define: {
    // 去除vue的options api
    // 不能去除，不能保证组件库完全为Composition API，去掉可能导致组件库功能丢失
    // __VUE_OPTIONS_API__: false
  },
  css: {
    preprocessorOptions: {
      less: {
        modifyVars: {
          'arcoblue-6': primaryColor
        },
        javascriptEnabled: true
      },
      scss: {
        additionalData: `@import "@/styles/variable.scss";`
      }
    }
  },
  plugins: [
    vue(),
    AutoImport({
      eslintrc: {
        enabled: true,
        filepath: './.eslintrc-auto-import.json',
        globalsPropValue: true
      },
      imports: ['vue', '@vueuse/core', 'pinia']
    }),
    UnoCSS(),
    Components({
      resolvers: [ArcoResolver()]
    }),
    chunkSplitPlugin({
      strategy: 'default',
      customSplitting: {
        customize: [/src\/utils/, /src\/assets/],
        componentLibrary: ['@arco-design/web-vue']
      }
    })
  ],
  resolve: {
    alias: {
      '@': resolve(__dirname, './src')
    }
  },
  build: {
    assetsInlineLimit: 4096,
    cssCodeSplit: true,
    sourcemap: false,
    minify: 'terser',
    terserOptions: {
      compress: {
        drop_console: true,
        drop_debugger: true
      }
    }
  }
})

```

**Comment by lainbo** [comment]
> > single-vendor 模式吗？升级了插件版本没？
> 
> 已经升级到0.2.5了 以下是我的vite.config.js
> 
> ```js
> import { defineConfig } from 'vite'
> import { resolve } from 'path'
> import { chunkSplitPlugin } from 'vite-plugin-chunk-split'
> import vue from '@vitejs/plugin-vue'
> import Components from 'unplugin-vue-components/vite'
> import AutoImport from 'unplugin-auto-import/vite'
> import UnoCSS from 'unocss/vite'
> import { ArcoResolver } from 'unplugin-vue-components/resolvers'
> import { primaryColor } from './src/config/colorConfig.js'
> 
> export default defineConfig({
>   base: './',
>   define: {
>     // 去除vue的options api
>     // 不能去除，不能保证组件库完全为Composition API，去掉可能导致组件库功能丢失
>     // __VUE_OPTIONS_API__: false
>   },
>   css: {
>     preprocessorOptions: {
>       less: {
>         modifyVars: {
>           'arcoblue-6': primaryColor
>         },
>         javascriptEnabled: true
>       },
>       scss: {
>         additionalData: `@import "@/styles/variable.scss";`
>       }
>     }
>   },
>   plugins: [
>     vue(),
>     AutoImport({
>       eslintrc: {
>         enabled: true,
>         filepath: './.eslintrc-auto-import.json',
>         globalsPropValue: true
>       },
>       imports: ['vue', '@vueuse/core', 'pinia']
>     }),
>     UnoCSS(),
>     Components({
>       resolvers: [ArcoResolver()]
>     }),
>     chunkSplitPlugin({
>       strategy: 'default',
>       customSplitting: {
>         customize: [/src\/utils/, /src\/assets/],
>         componentLibrary: ['@arco-design/web-vue']
>       }
>     })
>   ],
>   resolve: {
>     alias: {
>       '@': resolve(__dirname, './src')
>     }
>   },
>   build: {
>     assetsInlineLimit: 4096,
>     cssCodeSplit: true,
>     sourcemap: false,
>     minify: 'terser',
>     terserOptions: {
>       compress: {
>         drop_console: true,
>         drop_debugger: true
>       }
>     }
>   }
> })
> ```

生成的js如下，是不是我哪里没有写对~
![image](https://user-images.githubusercontent.com/46062895/180802730-1abce530-963e-4681-be81-6299c766e59f.png)

**Comment by sanyuan0704** [comment]
vite 3.0.3，我并没有复现你的问题

**Comment by sanyuan0704** [comment]
![image](https://user-images.githubusercontent.com/39261479/180803952-394d501d-95cc-4490-ba2d-01d4bb4886cb.png)
![image](https://user-images.githubusercontent.com/39261479/180804054-59da187b-06a9-47a5-a12d-9498c7befea3.png)

**Comment by lainbo** [comment]
> ![image](https://user-images.githubusercontent.com/39261479/180803952-394d501d-95cc-4490-ba2d-01d4bb4886cb.png) ![image](https://user-images.githubusercontent.com/39261479/180804054-59da187b-06a9-47a5-a12d-9498c7befea3.png)



我完全按照您的写法重新创建了一个Vite3项目，打包后还是没有相关的js文件，如下图
![image](https://user-images.githubusercontent.com/46062895/180816447-24618723-b7fc-4a4b-b289-1d91add9e132.png)

但是如果我将vite退回2.9.14，他就可以正常运行了
![image](https://user-images.githubusercontent.com/46062895/180816280-db3c892c-8d76-44c3-83f7-f90b4bdb695a.png)

这是我的相关系统信息
  System:
    OS: Windows 10 10.0.22000
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i7-12700KF
    Memory: 8.57 GB / 15.86 GB
  Binaries:
    Node: 16.15.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
    npm: 8.11.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (103.0.1264.71)
    Internet Explorer: 11.0.22000.120

**Comment by sanyuan0704** [comment]
现在已经解决了哈

**Comment by lainbo** [comment]
> 现在已经解决了哈

嗯嗯，已解决！大佬很强！！！
